site_name: Wiki-Kingen
site_author: Kingen
site_url: https://eastsunrise.github.io/wiki-kingen/
repo_url: https://github.com/eastsunrise/wiki-kingen/
edit_uri: edit/master/docs
use_directory_urls: false
dev_addr: 127.0.0.1:4000
docs_dir: docs
site_dir: site
theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/Ceil.png
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
      primary: indigo
      accent: blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式
      primary: indigo
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - content.code.copy
    - content.action.view
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
extra:
  generator: false
  alternate:
    - name: 中文
      link: /wiki-kingen/
      lang: zh
    - name: English
      link: /wiki-kingen/en/
      lang: en
extra_javascript:
  - assets/javascripts/kingen.js
  - assets/javascripts/katex/katex.js
  - assets/javascripts/katex/katex.min.js
extra_css:
  - assets/stylesheets/material-custom.css
  - assets/stylesheets/katex/katex.min.css
plugins:
  - search
  - git-revision-date-localized:
      type: iso_date
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          percent_encode: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: index.md
  - Java:
      - java/index.md
      - 基础语法:
          - Annotation: java/basic/annotation.md
      - 扩展库:
          - Apache Commons: java/lib/apache-commons.md
          - Apache POI: java/lib/apache-poi.md
          - HttpComponents: java/lib/http-components.md
          - Lombok: java/lib/lombok.md
          - Fastjson: java/lib/fastjson.md
          - Jsoup: java/lib/jsoup.md
      - 设计模式:
          - 状态模式: java/design-pattern/state-pattern.md
          - 单例模式: java/design-pattern/singleton-pattern.md
      - Spring:
          - java/spring/index.md
          - AOP: java/spring/aop.md
          - Transaction: java/spring/transaction.md
          - Actuator: java/spring/actuator.md
      - MyBatis: java/mybatis.md
      - Tomcat: java/tomcat.md
      - Maven: java/maven.md
      - Freemarker: java/freemarker.md
      - OGNL: java/ognl.md
      - Quarkus: java/quarkus.md
  - CS:
      - 数学:
          - 求和公式: cs/math/summation.md
          - 正态分布: cs/math/normal-distribution.md
          - 线性代数: cs/math/linear-algebra.md
          - 傅里叶变换: cs/math/fourier-transform.md
      - 算法:
          - cs/algo/index.md
          - 排序:
              - cs/algo/sort/index.md
              - 选择排序: cs/algo/sort/selection-sort.md
              - 冒泡排序: cs/algo/sort/bubble-sort.md
              - 插入排序: cs/algo/sort/insertion-sort.md
              - 归并排序: cs/algo/sort/merge-sort.md
              - 快速排序: cs/algo/sort/quick-sort.md
              - 计数排序: cs/algo/sort/counting-sort.md
              - 桶排序: cs/algo/sort/bucket-sort.md
          - 分治算法: cs/algo/divide-and-conquer.md
          - 动态规划: cs/algo/dynamic-programming.md
          - 贪心算法: cs/algo/greedy-algorithm.md
          - 回溯算法: cs/algo/backtracking.md
          - 分支界定: cs/algo/branch-and-bound.md
          - 模式匹配:
              - KMP 算法: cs/algo/pattern-searching/kmp-algorithm.md
              - BM 算法: cs/algo/pattern-searching/bm-algorithm.md
              - Sunday 算法: cs/algo/pattern-searching/sunday-algorithm.md
          - 密钥算法:
              - RSA: cs/algo/crypto/rsa.md
              - SHA: cs/algo/crypto/sha.md
          - 图论:
              - 深度优先搜索: cs/algo/graph/dfs.md
              - Dijkstra's 算法: cs/algo/graph/dijkstra's-algorithm.md
              - Tarjan 算法: cs/algo/graph/tarjan-algorithm.md
          - 其它算法:
              - Knuth 洗牌算法: cs/algo/others/knuth-shuffle-algorithm.md
              - 蒙特卡洛树搜索: cs/algo/others/monte-carlo-tree-search.md
              - 蓄水池抽样算法: cs/algo/others/reservoir-sampling.md
      - 数据结构:
          - cs/ds/index.md
          - 二叉树: cs/ds/binary-tree.md
          - 二叉搜索树: cs/ds/binary-search-tree.md
          - 堆: cs/ds/heap.md
          - 线段树: cs/ds/segment-tree.md
          - 红黑树: cs/ds/red-black-tree.md
          - 单调栈: cs/ds/monotonic-stack.md
          - 并查集: cs/ds/disjoint-set.md
          - 跳表: cs/ds/skip-list.md
      - 机器学习:
          - cs/ml/index.md
          - 神经网络: cs/ml/neural-networks.md
          - 卷积神经网络: cs/ml/convolutional-neural-networks.md
      - Problem:
          - 逆序对: cs/problem/inversion-pairs.md
  - Python:
      - py/index.md
      - 标准库:
          - 文件和目录访问:
              - shutil: py/lib/shutil.md
          - 数据持久化:
              - sqlite3: py/lib/sqlite3.md
          - 文件格式:
              - configParser: py/lib/configparser.md
          - 加密服务:
              - hashlib: py/lib/hashlib.md
          - 操作系统服务:
              - logging: py/lib/logging.md
          - 互联网协议和支持:
              - urllib: py/lib/urllib.md
          - GUI:
              - tkinter: py/lib/tkinter.md
      - 扩展库:
          - BeautifulSoup: py/lib/bs4.md
          - PyMySQL: py/lib/pymysql.md
          - PyYAML: py/lib/pyyaml.md
          - PyWin32: py/lib/pywin32.md
          - MkDocs: py/lib/mkdocs.md
      - 应用:
          - 爬虫: py/app/spider.md
          - 任务: py/app/task.md
          - Excel: py/app/excel.md
      - Numpy: py/numpy.md
      - Pandas: py/pandas.md
      - Matplotlib: py/matplotlib.md
      - Flask: py/flask.md
  - Development:
      - References: dev/references.md
      - API:
          - 豆瓣: dev/api/douban.md
          - 酷狗: dev/api/kugou.md
          - 英雄联盟: dev/api/lol.md
      - 数据库:
          - MySQL:
              - dev/db/mysql/index.md
              - SQL: dev/db/mysql/sql.md
              - FAQ: dev/db/mysql/faq.md
          - Oracle:
              - dev/db/oracle/index.md
              - SQL: dev/db/oracle/sql.md
          - Redis: dev/db/redis.md
          - InfluxDB: dev/db/influxdb.md
          - IoTDB: dev/db/iotdb.md
          - SQLite: dev/db/sqlite.md
      - Web:
          - JavaScript:
              - dev/web/js/index.md
              - jQuery: dev/web/js/jquery.md
              - Node.js: dev/web/js/nodejs.md
              - React: dev/web/js/react.md
              - Layui: dev/web/js/layui.md
              - Select2: dev/web/js/select2.md
          - CSS:
              - Bootstrap: dev/web/css/bootstrap.md
      - Languages:
          - Go: dev/lang/go.md
          - C Language: dev/lang/c.md
          - PHP: dev/lang/php.md
      - Linux: dev/linux.md
      - Git: dev/git.md
      - Docker: dev/docker.md
      - Kafka: dev/kafka.md
      - Nginx: dev/nginx.md
      - Prometheus: dev/prometheus.md
      - Grafana: dev/grafana.md
      - FTP: dev/ftp.md
      - OAuth: dev/oauth.md
      - FasfDFS: dev/fastdfs.md
      - MinIO: dev/minio.md
      - MQTT: dev/mqtt.md
  - Misc:
      - ChatGPT: misc/chatgpt.md
      - Activation: misc/activation.md
      - Wiki: misc/wiki.md
      - LaTeX: misc/latex.md
      - Markdown: misc/markdown.md
      - Chrome: misc/chrome.md
      - Windows: misc/windows.md
      - IntelliJ IDEA: misc/idea.md
      - Visual Studio Code: misc/vscode.md
      - Fiddler: misc/fiddler.md
      - Charles: misc/charles.md
      - FFmpeg: misc/ffmpeg.md
