site_name: Wiki-Kingen
site_author: Kingen
site_url: https://eastsunrise.github.io/wiki-kingen/
repo_url: https://github.com/eastsunrise/wiki-kingen/
edit_uri: edit/master/docs
use_directory_urls: false
dev_addr: 127.0.0.1:4000
docs_dir: docs
site_dir: site
theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/Ceil.png
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
      primary: indigo
      accent: blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式
      primary: indigo
      accent: blue
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - content.code.copy
    - content.action.view
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
extra:
  generator: false
  alternate:
    - name: 中文
      link: /wiki-kingen/
      lang: zh
    - name: English
      link: /wiki-kingen/en/
      lang: en
extra_javascript:
  - assets/javascripts/kingen.js
  - assets/javascripts/katex/katex.js
  - assets/javascripts/katex/katex.min.js
  - assets/javascripts/massiliaGraphviz.js
extra_css:
  - assets/stylesheets/material-custom.css
  - assets/stylesheets/katex/katex.min.css
plugins:
  - search
  - git-revision-date-localized:
      timezone: Asia/Shanghai
      type: iso_date
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - meta
  - mkdocs_graphviz
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          percent_encode: true
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: index.md
  - Java:
      - Core:
          - Get Started: java/core/index.md
          - Annotation: java/core/annotation.md
          - Generic: java/core/generic.md
          - Exception: java/core/exception.md
          - I/O: java/core/io.md
          - Collection: java/core/collection.md
          - Concurrency: java/core/concurrency.md
          - Reflection: java/core/reflection.md
          - JVM: java/core/jvm.md
          - GC: java/core/gc.md
          - FAQ: java/core/faq.md
      - Spring:
          - Spring Framework:
              - IoC: java/spring/spring-framework/ioc.md
              - AOP: java/spring/spring-framework/aop.md
              - Spring Web MVC: java/spring/spring-framework/web-mvc.md
              - Transaction: java/spring/spring-framework/transaction.md
          - Spring Boot:
              - Get Started: java/spring/spring-boot/index.md
              - Actuator: java/spring/spring-boot/actuator.md
          - Spring Data:
              - Spring Data Elasticsearch: java/spring/spring-data/elasticsearch.md
          - Spring Security: java/spring/spring-security.md
          - Spring Batch: java/spring/spring-batch.md
          - Spring LDAP: java/spring/spring-ldap.md
      - Libraries:
          - Apache Commons: java/lib/apache-commons.md
          - Apache POI: java/lib/apache-poi.md
          - HttpComponents: java/lib/http-components.md
          - Lombok: java/lib/lombok.md
          - Fastjson: java/lib/fastjson.md
          - Jsoup: java/lib/jsoup.md
      - 设计模式:
          - 状态模式: java/design-pattern/state-pattern.md
          - 单例模式: java/design-pattern/singleton-pattern.md
      - MyBatis: java/mybatis.md
      - Tomcat: java/tomcat.md
      - Netty: java/netty.md
      - Quartz: java/quartz.md
      - Maven: java/maven.md
      - Freemarker: java/freemarker.md
      - OGNL: java/ognl.md
      - Quarkus: java/quarkus.md
  - CS:
      - 数学:
          - 微积分:
              - 泰勒定理: cs/math/calculus/taylor-theorem.md
          - 数论:
              - 欧拉定理: cs/math/number-theory/euler-theorem.md
              - 费马平方和定理: cs/math/number-theory/fermat-theorem-on-sums-of-two-squares.md
          - 求和公式: cs/math/summation.md
          - 正态分布: cs/math/normal-distribution.md
          - 线性代数: cs/math/linear-algebra.md
          - 傅里叶变换: cs/math/fourier-transform.md
      - 数据结构:
          - cs/ds/index.md
          - 树:
              - 二叉树: cs/ds/tree/binary-tree.md
              - 二叉搜索树: cs/ds/tree/binary-search-tree.md
              - AVL树: cs/ds/tree/avl-tree.md
              - 红黑树: cs/ds/tree/red-black-tree.md
              - B+树: cs/ds/tree/b+tree.md
              - 线段树: cs/ds/tree/segment-tree.md
          - 堆: cs/ds/heap.md
          - 散列表: cs/ds/hash-table.md
          - 图: cs/ds/graph.md
          - 单调栈: cs/ds/monotonic-stack.md
          - 并查集: cs/ds/disjoint-set.md
          - 跳表: cs/ds/skip-list.md
          - 布隆过滤器: cs/ds/bloom-filter.md
      - 算法:
          - 算法分析: cs/algo/index.md
          - 排序:
              - 选择排序: cs/algo/sort/selection-sort.md
              - 冒泡排序: cs/algo/sort/bubble-sort.md
              - 插入排序: cs/algo/sort/insertion-sort.md
              - 归并排序: cs/algo/sort/merge-sort.md
              - 快速排序: cs/algo/sort/quick-sort.md
              - 计数排序: cs/algo/sort/counting-sort.md
              - 桶排序: cs/algo/sort/bucket-sort.md
              - 拓扑排序: cs/algo/sort/topological-sort.md
          - 分治算法: cs/algo/divide-and-conquer.md
          - 动态规划: cs/algo/dynamic-programming.md
          - 贪心算法: cs/algo/greedy-algorithm.md
          - 回溯算法: cs/algo/backtracking.md
          - 分支界定: cs/algo/branch-and-bound.md
          - 模式匹配:
              - KMP 算法: cs/algo/pattern-searching/kmp-algorithm.md
              - BM 算法: cs/algo/pattern-searching/bm-algorithm.md
              - Sunday 算法: cs/algo/pattern-searching/sunday-algorithm.md
              - AC 自动机: cs/algo/pattern-searching/ac-automaton.md
          - 密钥算法:
              - RSA: cs/algo/crypto/rsa.md
              - SHA: cs/algo/crypto/sha.md
          - 图算法:
              - Dijkstra 算法: cs/algo/graph/dijkstra-algorithm.md
              - Floyd 算法: cs/algo/graph/floyd-algorithm.md
              - Tarjan 算法: cs/algo/graph/tarjan-algorithm.md
              - 最小生成树: cs/algo/graph/minimum-spanning-tree.md
              - A* 算法: cs/algo/graph/a-star.md
          - 其它算法:
              - Knuth 洗牌算法: cs/algo/others/knuth-shuffle-algorithm.md
              - 蒙特卡洛树搜索: cs/algo/others/monte-carlo-tree-search.md
              - 蓄水池抽样算法: cs/algo/others/reservoir-sampling.md
              - Gosper's Hack: cs/algo/others/gosper-hack.md
              - Manachar 算法: cs/algo/others/manachar-algorithm.md
              - 相似性算法: cs/algo/others/similarity.md
      - 机器学习:
          - cs/ml/index.md
          - 神经网络: cs/ml/neural-networks.md
          - 卷积神经网络: cs/ml/convolutional-neural-networks.md
      - Problem:
          - 逆序对: cs/problem/inversion-pairs.md
  - Python:
      - Core:
          - Get Started: py/core/index.md
          - 文件和目录访问:
              - shutil: py/core/shutil.md
          - 数据持久化:
              - sqlite3: py/core/sqlite3.md
          - 文件格式:
              - configParser: py/core/configparser.md
          - 加密服务:
              - hashlib: py/core/hashlib.md
          - 操作系统服务:
              - logging: py/core/logging.md
          - 互联网协议和支持:
              - urllib: py/core/urllib.md
          - GUI:
              - tkinter: py/core/tkinter.md
      - Libraries:
          - BeautifulSoup: py/lib/bs4.md
          - PyMySQL: py/lib/pymysql.md
          - PyYAML: py/lib/pyyaml.md
          - PyWin32: py/lib/pywin32.md
      - 应用:
          - 爬虫: py/app/spider.md
          - 任务: py/app/task.md
          - Excel: py/app/excel.md
      - Numpy: py/numpy.md
      - Pandas: py/pandas.md
      - Matplotlib: py/matplotlib.md
      - Flask: py/flask.md
  - Development:
      - References: dev/references.md
      - 数据库:
          - 事务: dev/db/transaction.md
          - MySQL:
              - dev/db/mysql/index.md
              - SQL:
                  - DDL: dev/db/mysql/sql/ddl.md
                  - DML: dev/db/mysql/sql/dml.md
                  - DCL: dev/db/mysql/sql/dcl.md
              - 函数和操作符: dev/db/mysql/func&ops.md
              - 优化:
                  - SQL优化: dev/db/mysql/optimization/sql-optimization.md
                  - 索引优化: dev/db/mysql/optimization/index-optimization.md
                  - 查询执行计划: dev/db/mysql/optimization/query-execution-plan.md
              - 分区: dev/db/mysql/partitioning.md
              - Programs: dev/db/mysql/programs.md
              - FAQ: dev/db/mysql/faq.md
          - MongoDB:
              - dev/db/mongodb/index.md
              - 分片: dev/db/mongodb/sharding.md
              - Change Streams: dev/db/mongodb/change-streams.md
              - Reference: dev/db/mongodb/reference.md
              - Tools: dev/db/mongodb/tools.md
              - FAQ: dev/db/mongodb/faq.md
          - Oracle:
              - dev/db/oracle/index.md
              - SQL: dev/db/oracle/sql.md
          - Redis: dev/db/redis.md
          - InfluxDB: dev/db/influxdb.md
          - IoTDB: dev/db/iotdb.md
          - PostgreSQL: dev/db/postgresql.md
          - SQLite: dev/db/sqlite.md
      - Web:
          - HTTP: dev/web/http.md
          - JavaScript:
              - dev/web/js/index.md
              - 客户端 Web API: dev/web/js/client-side-web-apis.md
              - Node.js: dev/web/js/nodejs.md
              - React:
                  - dev/web/js/react/index.md
                  - React Router: dev/web/js/react/react-router.md
              - TypeScript: dev/web/js/typescript.md
              - Axios: dev/web/js/axios.md
              - jQuery: dev/web/js/jquery.md
              - Layui: dev/web/js/layui.md
              - Video.js: dev/web/js/video.js.md
              - Hammer.js: dev/web/js/hammer.js.md
          - CSS:
              - Bootstrap: dev/web/css/bootstrap.md
          - Vite: dev/web/vite.md
      - Languages:
          - Go: dev/lang/go.md
          - C Language: dev/lang/c.md
          - C#: dev/lang/c#.md
          - PHP: dev/lang/php.md
      - 中间件:
          - Kafka: dev/mw/kafka.md
          - RabbitMQ: dev/mw/rabbitmq.md
          - ElasticSearch: dev/mw/elasticsearch.md
          - ZooKeeper: dev/mw/zookeeper.md
      - Linux: dev/linux.md
      - Git: dev/git.md
      - Docker: dev/docker.md
      - Kubernetes: dev/k8s.md
      - Nginx: dev/nginx.md
      - Prometheus: dev/prometheus.md
      - GraphQL: dev/graphql.md
      - Grafana: dev/grafana.md
      - FTP: dev/ftp.md
      - Rest API: dev/rest-api.md
      - OAuth: dev/oauth.md
      - FasfDFS: dev/fastdfs.md
      - MinIO: dev/minio.md
      - MQTT: dev/mqtt.md
  - Misc:
      - ChatGPT: misc/chatgpt.md
      - Activation: misc/activation.md
      - Wiki: misc/wiki.md
      - LaTeX: misc/latex.md
      - Markdown: misc/markdown.md
      - MkDocs: misc/mkdocs.md
      - Mermaid: misc/mermaid.md
      - Excel: misc/excel.md
      - Chrome: misc/chrome.md
      - Windows: misc/windows.md
      - IntelliJ IDEA: misc/idea.md
      - Visual Studio Code: misc/vscode.md
      - Fiddler: misc/fiddler.md
      - Charles: misc/charles.md
      - FFmpeg: misc/ffmpeg.md
      - Clash: misc/clash.md
