site_name: Kingen
dev_addr: 127.0.0.1:9999
repo_name: Gitee
repo_url: https://gitee.com/eastsunrise/wiki-kingen/
edit_uri: edit/master/docs
site_author: Kingen
use_directory_urls: false
theme:
  name: mkdocs
  navigation_depth: 6
extra_javascript:
  - static/js/kingen.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - static/css/kingen.css
markdown_extensions:
  - extra
  - admonition
  - codehilite
  - legacy_attrs
  - legacy_em
  - meta
  - nl2br
  - sane_lists
  - smarty
  - toc
  - wikilinks
  - mdx_math:
      enable_dollar_delimiter: True
nav:
  - Home: index.md
  - Java:
        - Get Started: java/index.md
        - Language References:
              - Annotations: java/language/annotations.md
              - Collection: java/language/collection.md
        - Library References:
              - Fastjson: java/library/fastjson.md
              - Apache Commons: java/library/apache-commons.md
              - Apache POI: java/library/apache-poi.md
              - Lombok: java/library/lombok.md
        - Design Patterns:
              - State Pattern: java/design/state.md
              - Singleton Pattern: java/design/singleton.md
        - Spring Framework:
              - Get Started: java/spring/index.md
              - Aspect Oriented Programming: java/spring/aop.md
              - Transaction: java/spring/transaction.md
        - Spring Boot:
              - Get Started: java/spring-boot/index.md
        - MyBatis:
              - MyBatis: java/mybatis/index.md
              - Generator: java/mybatis/generator.md
        - Tomcat: java/tomcat.md
        - Maven: java/maven.md
        - Freemarker: java/freemarker.md
        - OGNL: java/ognl.md
  - CS:
        - Mathematics:
              - Fourier Transform: cs/mathematics/fourier-transform.md
        - Algorithms:
              - Analysis of Algorithms:
                    - Asymptotic Analysis: cs/algorithms/analysis/asymptotic-analysis.md
              - Sorting:
                    - Quick Sort: cs/algorithms/sorting/quick-sort.md
                    - Merge Sort: cs/algorithms/sorting/merge-sort.md
                    - Heap Sort: cs/algorithms/sorting/heap-sort.md
                    - Bucket Sort: cs/algorithms/sorting/bucket-sort.md
              - Divide and Conquer: cs/algorithms/divide-and-conquer.md
              - Greedy Algorithms: cs/algorithms/greedy-algorithms.md
              - Pattern Searching:
                    - Knuth-Morris-Pratt Algorithm: cs/algorithms/pattern-searching/Knuth-Morris-Pratt.md
                    - Boyer Moore Algorithm: cs/algorithms/pattern-searching/Boyer Moore Algorithm.md
              - Cryptography:
                    - RSA: cs/algorithms/cryptography/rsa.md
                    - SHA: cs/algorithms/cryptography/sha.md
              - Graph:
                    - Dijkstra's Algorithm: cs/algorithms/graph/Dijkstra's Algorithm.md
              - Other Algorithms:
                    - Knuth-Shuffle Algorithm: cs/algorithms/others/Knuth-Shuffle.md
                    - Monte Carlo Tree Search: cs/algorithms/others/Monte Carlo Tree Search.md
        - Data Structures:
              - Binary Tree: cs/data-structure/binary-tree.md
              - Binary Search Tree: cs/data-structure/binary-search-tree.md
              - Heap: cs/data-structure/heap.md
              - Disjoint Set: cs/data-structure/disjoint.md
        - Problems:
              - Inversion Pairs: cs/problems/inversion-pairs.md
  - Python:
        - Get Started: python/index.md
        - Library References:
              - Operating System Services:
                    - os: python/library/os.md
                    - logging: python/library/logging.md
              - Cryptographic Services:
                    - hashlib: python/library/hashlib.md
              - File Formats:
                    - configParser: python/library/configparser.md
              - File and Directory Access:
                    - shutil: python/library/shutil.md
              - Internet Protocols and Support:
                    - urllib: python/library/urllib.md
              - Graphical User Interfaces: python/library/tkinter.md
              - Data Persistence:
                    - sqlite3: python/library/sqlite3.md
        - Extension References:
              - BeautifulSoup: python/library/bs4.md
              - PyMySQL: python/library/pymysql.md
              - PyYAML: python/library/pyyaml.md
              - PyWin32: python/library/pywin32.md
        - Applications:
              - Spider: python/app/spider.md
              - Task: python/app/task.md
              - Excel: python/app/excel.md
        - Flask: python/flask.md
  - Development:
        - References: dev/references.md
        - APIs:
              - Douban: dev/apis/douban.md
              - Kugou: dev/apis/kugou.md
              - League of Legends: dev/apis/lol.md
        - MySQL:
              - Get Started: dev/mysql/index.md
              - FAQ: dev/mysql/faq.md
        - Oracle:
              - Get Stared: dev/oracle/index.md
              - SQL: dev/oracle/sql.md
        - Redis: dev/redis.md
        - SQLite: dev/sqlite.md
        - Nginx: dev/nginx.md
        - Git: dev/git.md
        - Linux: dev/linux.md
        - FTP: dev/ftp.md
        - Web:
              - Bootstrap: dev/web/bootstrap.md
        - JavaScript:
              - JavaScript: dev/js/index.md
              - jQuery: dev/js/jquery.md
              - React: dev/js/react.md
              - Node.js: dev/js/nodejs.md
              - Select2: dev/js/select2.md
              - Layer: dev/js/layer.md
        - PHP:
              - Get Started: dev/php.md
        - OAuth: dev/oauth.md
  - Misc:
        - Activation: misc/activation.md
        - Wiki: misc/wiki.md
        - LaTeX: misc/latex.md
        - Markdown: misc/markdown.md
        - Chrome: misc/chrome.md
        - Windows: misc/windows.md
        - IntelliJ IDEA: misc/idea.md
        - Visual Studio Code: misc/vscode.md
        - Fiddler: misc/fiddler.md
        - Charles: misc/charles.md
